"use client";

import { useState } from "react";

export default function ImportEditionPage() {
  const [file, setFile] = useState(null);
  const [secret, setSecret] = useState("");
  const [publish, setPublish] = useState(false);
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(false);

  async function handleImport() {
    if (!file) {
      setMessage("Please select the generated articles.json file.");
      return;
    }

    if (!secret.trim()) {
      setMessage("Please enter the newsroom import secret.");
      return;
    }

    setLoading(true);
    setMessage("");

    try {
      const fileText = await file.text();
      const payload = JSON.parse(fileText);

      payload.publish = publish;

      const response = await fetch("/api/admin/import-edition", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-newsroom-secret": secret.trim(),
        },
        body: JSON.stringify(payload),
      });

      const result = await response.json();

      if (!response.ok) {
        throw new Error(result.error || "Edition import failed.");
      }

      const summary = result.results
        .map(
          (item) =>
            `${item.language}: ${item.articleCount} articles (${item.status})`
        )
        .join(" | ");

      setMessage(`Edition imported successfully. ${summary}`);
    } catch (error) {
      if (error instanceof SyntaxError) {
        setMessage(
          "The selected file is not valid JSON. Select 06_WEB_OUTPUT/articles.json."
        );
      } else {
        setMessage(error.message || "Edition import failed.");
      }
    } finally {
      setLoading(false);
    }
  }

  return (
    <main className="min-h-screen bg-slate-100 px-4 py-12">
      <div className="mx-auto max-w-2xl overflow-hidden rounded-2xl bg-white shadow-xl">
        <div className="bg-slate-950 px-8 py-7 text-white">
          <p className="text-sm font-semibold uppercase tracking-widest text-amber-400">
            The Aspire Nation
          </p>

          <h1 className="mt-2 text-3xl font-bold">
            Import Newspaper Edition
          </h1>

          <p className="mt-2 text-sm text-slate-300">
            Upload the JSON file generated by the AI Newsroom.
          </p>
        </div>

        <div className="space-y-6 p-8">
          <div>
            <label className="mb-2 block text-sm font-semibold text-slate-800">
              Edition JSON File
            </label>

            <input
              type="file"
              accept=".json,application/json"
              onChange={(event) =>
                setFile(event.target.files?.[0] || null)
              }
              className="block w-full rounded-xl border border-slate-300 bg-white p-3 text-sm"
            />

            <p className="mt-2 text-xs text-slate-500">
              Select: 06_WEB_OUTPUT/articles.json
            </p>
          </div>

          <div>
            <label className="mb-2 block text-sm font-semibold text-slate-800">
              Newsroom Import Secret
            </label>

            <input
              type="password"
              value={secret}
              onChange={(event) => setSecret(event.target.value)}
              placeholder="Enter your private import secret"
              autoComplete="off"
              className="w-full rounded-xl border border-slate-300 p-3 outline-none focus:border-slate-700"
            />
          </div>

          <label className="flex cursor-pointer items-start gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4">
            <input
              type="checkbox"
              checked={publish}
              onChange={(event) => setPublish(event.target.checked)}
              className="mt-1 h-4 w-4"
            />

            <span>
              <span className="block font-semibold text-slate-900">
                Publish immediately
              </span>

              <span className="mt-1 block text-sm text-slate-600">
                Leave this unchecked for the first test. The edition will be
                saved with review status.
              </span>
            </span>
          </label>

          <button
            type="button"
            onClick={handleImport}
            disabled={loading}
            className="w-full rounded-xl bg-slate-950 px-5 py-3.5 font-semibold text-white transition hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-50"
          >
            {loading ? "Importing Edition..." : "Import Edition"}
          </button>

          {message && (
            <div className="rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-800">
              {message}
            </div>
          )}
        </div>
      </div>
    </main>
  );
}